//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrisisInterfere.DynamicEstimateService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DynamicEstimateSearchModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.DynamicEstimateModel")]
    [System.SerializableAttribute()]
    public partial class DynamicEstimateSearchModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WarningLevelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((this.DepartmentIDField.Equals(value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndIndex {
            get {
                return this.EndIndexField;
            }
            set {
                if ((this.EndIndexField.Equals(value) != true)) {
                    this.EndIndexField = value;
                    this.RaisePropertyChanged("EndIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EndTimeField, value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartIndex {
            get {
                return this.StartIndexField;
            }
            set {
                if ((this.StartIndexField.Equals(value) != true)) {
                    this.StartIndexField = value;
                    this.RaisePropertyChanged("StartIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StartTimeField, value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WarningLevel {
            get {
                return this.WarningLevelField;
            }
            set {
                if ((this.WarningLevelField.Equals(value) != true)) {
                    this.WarningLevelField = value;
                    this.RaisePropertyChanged("WarningLevel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DynamicEstimateViewModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.DynamicEstimateModel")]
    [System.SerializableAttribute()]
    public partial class DynamicEstimateViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CounselorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DyEstiIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DynamicEstimateContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DynamicEstimateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarningStateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CounselorName {
            get {
                return this.CounselorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CounselorNameField, value) != true)) {
                    this.CounselorNameField = value;
                    this.RaisePropertyChanged("CounselorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DyEstiID {
            get {
                return this.DyEstiIDField;
            }
            set {
                if ((this.DyEstiIDField.Equals(value) != true)) {
                    this.DyEstiIDField = value;
                    this.RaisePropertyChanged("DyEstiID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DynamicEstimateContent {
            get {
                return this.DynamicEstimateContentField;
            }
            set {
                if ((object.ReferenceEquals(this.DynamicEstimateContentField, value) != true)) {
                    this.DynamicEstimateContentField = value;
                    this.RaisePropertyChanged("DynamicEstimateContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DynamicEstimateDate {
            get {
                return this.DynamicEstimateDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DynamicEstimateDateField, value) != true)) {
                    this.DynamicEstimateDateField = value;
                    this.RaisePropertyChanged("DynamicEstimateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarningState {
            get {
                return this.WarningStateField;
            }
            set {
                if ((object.ReferenceEquals(this.WarningStateField, value) != true)) {
                    this.WarningStateField = value;
                    this.RaisePropertyChanged("WarningState");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DynamicEstimateReportModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.DynamicEstimateModel")]
    [System.SerializableAttribute()]
    public partial class DynamicEstimateReportModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CounselorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DynamicEstimateContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WarningLevelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CounselorID {
            get {
                return this.CounselorIDField;
            }
            set {
                if ((this.CounselorIDField.Equals(value) != true)) {
                    this.CounselorIDField = value;
                    this.RaisePropertyChanged("CounselorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DynamicEstimateContent {
            get {
                return this.DynamicEstimateContentField;
            }
            set {
                if ((object.ReferenceEquals(this.DynamicEstimateContentField, value) != true)) {
                    this.DynamicEstimateContentField = value;
                    this.RaisePropertyChanged("DynamicEstimateContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WarningLevel {
            get {
                return this.WarningLevelField;
            }
            set {
                if ((this.WarningLevelField.Equals(value) != true)) {
                    this.WarningLevelField = value;
                    this.RaisePropertyChanged("WarningLevel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DynamicEstimateService.IDynamicEstimateService")]
    public interface IDynamicEstimateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDynamicEstimateService/InitialDynamicEstimateTable", ReplyAction="http://tempuri.org/IDynamicEstimateService/InitialDynamicEstimateTableResponse")]
        System.Data.DataSet InitialDynamicEstimateTable(CrisisInterfere.DynamicEstimateService.DynamicEstimateSearchModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDynamicEstimateService/GetDynamicEstimateByUserID", ReplyAction="http://tempuri.org/IDynamicEstimateService/GetDynamicEstimateByUserIDResponse")]
        System.Collections.Generic.List<CrisisInterfere.DynamicEstimateService.DynamicEstimateViewModel> GetDynamicEstimateByUserID(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDynamicEstimateService/AddDynamicEstimate", ReplyAction="http://tempuri.org/IDynamicEstimateService/AddDynamicEstimateResponse")]
        int AddDynamicEstimate(CrisisInterfere.DynamicEstimateService.DynamicEstimateReportModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDynamicEstimateService/DeleteDynamicEstimate", ReplyAction="http://tempuri.org/IDynamicEstimateService/DeleteDynamicEstimateResponse")]
        int DeleteDynamicEstimate(int dyEstiID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDynamicEstimateService/AbsoluteDeleteDynamicEstimate", ReplyAction="http://tempuri.org/IDynamicEstimateService/AbsoluteDeleteDynamicEstimateResponse")]
        int AbsoluteDeleteDynamicEstimate(int userID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDynamicEstimateServiceChannel : CrisisInterfere.DynamicEstimateService.IDynamicEstimateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DynamicEstimateServiceClient : System.ServiceModel.ClientBase<CrisisInterfere.DynamicEstimateService.IDynamicEstimateService>, CrisisInterfere.DynamicEstimateService.IDynamicEstimateService {
        
        public DynamicEstimateServiceClient() {
        }
        
        public DynamicEstimateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DynamicEstimateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DynamicEstimateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DynamicEstimateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet InitialDynamicEstimateTable(CrisisInterfere.DynamicEstimateService.DynamicEstimateSearchModel model) {
            return base.Channel.InitialDynamicEstimateTable(model);
        }
        
        public System.Collections.Generic.List<CrisisInterfere.DynamicEstimateService.DynamicEstimateViewModel> GetDynamicEstimateByUserID(string userID) {
            return base.Channel.GetDynamicEstimateByUserID(userID);
        }
        
        public int AddDynamicEstimate(CrisisInterfere.DynamicEstimateService.DynamicEstimateReportModel model) {
            return base.Channel.AddDynamicEstimate(model);
        }
        
        public int DeleteDynamicEstimate(int dyEstiID) {
            return base.Channel.DeleteDynamicEstimate(dyEstiID);
        }
        
        public int AbsoluteDeleteDynamicEstimate(int userID) {
            return base.Channel.AbsoluteDeleteDynamicEstimate(userID);
        }
    }
}
