//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrisisInterfere.GroupReportService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExplainModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.GroupReportModel")]
    [System.SerializableAttribute()]
    public partial class ExplainModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DimensionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DimensionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndFractionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExplainCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExplainNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstSymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NormEndAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NormExplainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NormSexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NormStartAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondSymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartFractionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DimensionCode {
            get {
                return this.DimensionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DimensionCodeField, value) != true)) {
                    this.DimensionCodeField = value;
                    this.RaisePropertyChanged("DimensionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DimensionName {
            get {
                return this.DimensionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DimensionNameField, value) != true)) {
                    this.DimensionNameField = value;
                    this.RaisePropertyChanged("DimensionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndFraction {
            get {
                return this.EndFractionField;
            }
            set {
                if ((this.EndFractionField.Equals(value) != true)) {
                    this.EndFractionField = value;
                    this.RaisePropertyChanged("EndFraction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExplainCode {
            get {
                return this.ExplainCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExplainCodeField, value) != true)) {
                    this.ExplainCodeField = value;
                    this.RaisePropertyChanged("ExplainCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExplainName {
            get {
                return this.ExplainNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExplainNameField, value) != true)) {
                    this.ExplainNameField = value;
                    this.RaisePropertyChanged("ExplainName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstSymbol {
            get {
                return this.FirstSymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstSymbolField, value) != true)) {
                    this.FirstSymbolField = value;
                    this.RaisePropertyChanged("FirstSymbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NormEndAge {
            get {
                return this.NormEndAgeField;
            }
            set {
                if ((this.NormEndAgeField.Equals(value) != true)) {
                    this.NormEndAgeField = value;
                    this.RaisePropertyChanged("NormEndAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NormExplain {
            get {
                return this.NormExplainField;
            }
            set {
                if ((object.ReferenceEquals(this.NormExplainField, value) != true)) {
                    this.NormExplainField = value;
                    this.RaisePropertyChanged("NormExplain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NormSex {
            get {
                return this.NormSexField;
            }
            set {
                if ((this.NormSexField.Equals(value) != true)) {
                    this.NormSexField = value;
                    this.RaisePropertyChanged("NormSex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NormStartAge {
            get {
                return this.NormStartAgeField;
            }
            set {
                if ((this.NormStartAgeField.Equals(value) != true)) {
                    this.NormStartAgeField = value;
                    this.RaisePropertyChanged("NormStartAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondSymbol {
            get {
                return this.SecondSymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondSymbolField, value) != true)) {
                    this.SecondSymbolField = value;
                    this.RaisePropertyChanged("SecondSymbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartFraction {
            get {
                return this.StartFractionField;
            }
            set {
                if ((this.StartFractionField.Equals(value) != true)) {
                    this.StartFractionField = value;
                    this.RaisePropertyChanged("StartFraction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NormWarningModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.GroupReportModel")]
    [System.SerializableAttribute()]
    public partial class NormWarningModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndFractionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstSymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondSymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartFractionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarningCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndFraction {
            get {
                return this.EndFractionField;
            }
            set {
                if ((this.EndFractionField.Equals(value) != true)) {
                    this.EndFractionField = value;
                    this.RaisePropertyChanged("EndFraction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstSymbol {
            get {
                return this.FirstSymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstSymbolField, value) != true)) {
                    this.FirstSymbolField = value;
                    this.RaisePropertyChanged("FirstSymbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxAge {
            get {
                return this.MaxAgeField;
            }
            set {
                if ((this.MaxAgeField.Equals(value) != true)) {
                    this.MaxAgeField = value;
                    this.RaisePropertyChanged("MaxAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinAge {
            get {
                return this.MinAgeField;
            }
            set {
                if ((this.MinAgeField.Equals(value) != true)) {
                    this.MinAgeField = value;
                    this.RaisePropertyChanged("MinAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondSymbol {
            get {
                return this.SecondSymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondSymbolField, value) != true)) {
                    this.SecondSymbolField = value;
                    this.RaisePropertyChanged("SecondSymbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartFraction {
            get {
                return this.StartFractionField;
            }
            set {
                if ((this.StartFractionField.Equals(value) != true)) {
                    this.StartFractionField = value;
                    this.RaisePropertyChanged("StartFraction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarningCode {
            get {
                return this.WarningCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WarningCodeField, value) != true)) {
                    this.WarningCodeField = value;
                    this.RaisePropertyChanged("WarningCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GroupReportService.IGroupReportService")]
    public interface IGroupReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/AddGroupReport", ReplyAction="http://tempuri.org/IGroupReportService/AddGroupReportResponse")]
        bool AddGroupReport(string ansIDList, string reportName, string amountCode, string userIDList, string createPerson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/InitiGroupReportTable", ReplyAction="http://tempuri.org/IGroupReportService/InitiGroupReportTableResponse")]
        System.Data.DataSet InitiGroupReportTable(int userID, string reportName, string startDate, string endDate, int startPageIndex, int endPageIndex, string enterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/DeleteGroupReport", ReplyAction="http://tempuri.org/IGroupReportService/DeleteGroupReportResponse")]
        bool DeleteGroupReport(int grID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetReportTitle", ReplyAction="http://tempuri.org/IGroupReportService/GetReportTitleResponse")]
        string GetReportTitle(int grID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetAmountIntroduce", ReplyAction="http://tempuri.org/IGroupReportService/GetAmountIntroduceResponse")]
        string GetAmountIntroduce(int grID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetUserIDListAndAmountCode", ReplyAction="http://tempuri.org/IGroupReportService/GetUserIDListAndAmountCodeResponse")]
        System.Collections.Generic.List<string> GetUserIDListAndAmountCode(int grID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetAnswerAddRecord", ReplyAction="http://tempuri.org/IGroupReportService/GetAnswerAddRecordResponse")]
        string GetAnswerAddRecord(int uID, int ansID, string amountCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetAnswerAddRecordByAnsIDList", ReplyAction="http://tempuri.org/IGroupReportService/GetAnswerAddRecordByAnsIDListResponse")]
        System.Data.DataTable GetAnswerAddRecordByAnsIDList(string enterpriseCode, string AnsIDList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetDimensionByAmountCode", ReplyAction="http://tempuri.org/IGroupReportService/GetDimensionByAmountCodeResponse")]
        System.Collections.Generic.List<string> GetDimensionByAmountCode(string amountCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetDimensionByAmountCode_Name", ReplyAction="http://tempuri.org/IGroupReportService/GetDimensionByAmountCode_NameResponse")]
        System.Collections.Generic.Dictionary<string, string> GetDimensionByAmountCode_Name(string amountCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetNormExplainByDimensionCode", ReplyAction="http://tempuri.org/IGroupReportService/GetNormExplainByDimensionCodeResponse")]
        string GetNormExplainByDimensionCode(string dimensionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetNormExplainByDimensionCodeList", ReplyAction="http://tempuri.org/IGroupReportService/GetNormExplainByDimensionCodeListResponse")]
        System.Collections.Generic.Dictionary<string, string> GetNormExplainByDimensionCodeList(string dimensionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetSubjectCodeByDimensionCode", ReplyAction="http://tempuri.org/IGroupReportService/GetSubjectCodeByDimensionCodeResponse")]
        System.Collections.Generic.List<string> GetSubjectCodeByDimensionCode(string dimensionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetSubjectCodeByDimensionCodeList", ReplyAction="http://tempuri.org/IGroupReportService/GetSubjectCodeByDimensionCodeListResponse")]
        System.Data.DataTable GetSubjectCodeByDimensionCodeList(string dimensionCodeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetSingleScoreBySbjCodeAndOptCode", ReplyAction="http://tempuri.org/IGroupReportService/GetSingleScoreBySbjCodeAndOptCodeResponse")]
        string GetSingleScoreBySbjCodeAndOptCode(string optionCodeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetScoreTableByAmount_Code", ReplyAction="http://tempuri.org/IGroupReportService/GetScoreTableByAmount_CodeResponse")]
        System.Data.DataTable GetScoreTableByAmount_Code(string amount_Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetScoreModel", ReplyAction="http://tempuri.org/IGroupReportService/GetScoreModelResponse")]
        int GetScoreModel(string dimensionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetFormulaStrByDimensionCode", ReplyAction="http://tempuri.org/IGroupReportService/GetFormulaStrByDimensionCodeResponse")]
        string GetFormulaStrByDimensionCode(string dimensionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetFormulaStrByDimensionCodeList", ReplyAction="http://tempuri.org/IGroupReportService/GetFormulaStrByDimensionCodeListResponse")]
        System.Data.DataTable GetFormulaStrByDimensionCodeList(string dimensionCodeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetDimensionName", ReplyAction="http://tempuri.org/IGroupReportService/GetDimensionNameResponse")]
        string GetDimensionName(string dimensionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/NormCodeByDimensionCode", ReplyAction="http://tempuri.org/IGroupReportService/NormCodeByDimensionCodeResponse")]
        string NormCodeByDimensionCode(string dimensionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/NormCodeByDimensionCodeList", ReplyAction="http://tempuri.org/IGroupReportService/NormCodeByDimensionCodeListResponse")]
        System.Data.DataTable NormCodeByDimensionCodeList(string dimensionCodeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetExplainScoreByNormCodeTable", ReplyAction="http://tempuri.org/IGroupReportService/GetExplainScoreByNormCodeTableResponse")]
        System.Data.DataTable GetExplainScoreByNormCodeTable(string normCodeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetExplainScoreByNormCode", ReplyAction="http://tempuri.org/IGroupReportService/GetExplainScoreByNormCodeResponse")]
        System.Collections.Generic.List<CrisisInterfere.GroupReportService.ExplainModel> GetExplainScoreByNormCode(string normCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetNormWarningByNormCode", ReplyAction="http://tempuri.org/IGroupReportService/GetNormWarningByNormCodeResponse")]
        System.Collections.Generic.List<CrisisInterfere.GroupReportService.NormWarningModel> GetNormWarningByNormCode(string normCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetNormWarningByNormCodeList", ReplyAction="http://tempuri.org/IGroupReportService/GetNormWarningByNormCodeListResponse")]
        System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<CrisisInterfere.GroupReportService.NormWarningModel>> GetNormWarningByNormCodeList(string normCodeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetAnswerCreateTimeByUID", ReplyAction="http://tempuri.org/IGroupReportService/GetAnswerCreateTimeByUIDResponse")]
        string GetAnswerCreateTimeByUID(int uID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetAnswerCreateTimeByUIDList", ReplyAction="http://tempuri.org/IGroupReportService/GetAnswerCreateTimeByUIDListResponse")]
        System.Collections.Generic.List<string> GetAnswerCreateTimeByUIDList(string uID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetGroupReportCreateTime", ReplyAction="http://tempuri.org/IGroupReportService/GetGroupReportCreateTimeResponse")]
        string GetGroupReportCreateTime(int grID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetReportByReportName", ReplyAction="http://tempuri.org/IGroupReportService/GetReportByReportNameResponse")]
        int GetReportByReportName(string reportName, string enterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupReportService/GetScoreByAnswerID", ReplyAction="http://tempuri.org/IGroupReportService/GetScoreByAnswerIDResponse")]
        int GetScoreByAnswerID(int answerID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGroupReportServiceChannel : CrisisInterfere.GroupReportService.IGroupReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GroupReportServiceClient : System.ServiceModel.ClientBase<CrisisInterfere.GroupReportService.IGroupReportService>, CrisisInterfere.GroupReportService.IGroupReportService {
        
        public GroupReportServiceClient() {
        }
        
        public GroupReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GroupReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddGroupReport(string ansIDList, string reportName, string amountCode, string userIDList, string createPerson) {
            return base.Channel.AddGroupReport(ansIDList, reportName, amountCode, userIDList, createPerson);
        }
        
        public System.Data.DataSet InitiGroupReportTable(int userID, string reportName, string startDate, string endDate, int startPageIndex, int endPageIndex, string enterpriseCode) {
            return base.Channel.InitiGroupReportTable(userID, reportName, startDate, endDate, startPageIndex, endPageIndex, enterpriseCode);
        }
        
        public bool DeleteGroupReport(int grID) {
            return base.Channel.DeleteGroupReport(grID);
        }
        
        public string GetReportTitle(int grID) {
            return base.Channel.GetReportTitle(grID);
        }
        
        public string GetAmountIntroduce(int grID) {
            return base.Channel.GetAmountIntroduce(grID);
        }
        
        public System.Collections.Generic.List<string> GetUserIDListAndAmountCode(int grID) {
            return base.Channel.GetUserIDListAndAmountCode(grID);
        }
        
        public string GetAnswerAddRecord(int uID, int ansID, string amountCode) {
            return base.Channel.GetAnswerAddRecord(uID, ansID, amountCode);
        }
        
        public System.Data.DataTable GetAnswerAddRecordByAnsIDList(string enterpriseCode, string AnsIDList) {
            return base.Channel.GetAnswerAddRecordByAnsIDList(enterpriseCode, AnsIDList);
        }
        
        public System.Collections.Generic.List<string> GetDimensionByAmountCode(string amountCode) {
            return base.Channel.GetDimensionByAmountCode(amountCode);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetDimensionByAmountCode_Name(string amountCode) {
            return base.Channel.GetDimensionByAmountCode_Name(amountCode);
        }
        
        public string GetNormExplainByDimensionCode(string dimensionCode) {
            return base.Channel.GetNormExplainByDimensionCode(dimensionCode);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetNormExplainByDimensionCodeList(string dimensionCode) {
            return base.Channel.GetNormExplainByDimensionCodeList(dimensionCode);
        }
        
        public System.Collections.Generic.List<string> GetSubjectCodeByDimensionCode(string dimensionCode) {
            return base.Channel.GetSubjectCodeByDimensionCode(dimensionCode);
        }
        
        public System.Data.DataTable GetSubjectCodeByDimensionCodeList(string dimensionCodeList) {
            return base.Channel.GetSubjectCodeByDimensionCodeList(dimensionCodeList);
        }
        
        public string GetSingleScoreBySbjCodeAndOptCode(string optionCodeList) {
            return base.Channel.GetSingleScoreBySbjCodeAndOptCode(optionCodeList);
        }
        
        public System.Data.DataTable GetScoreTableByAmount_Code(string amount_Code) {
            return base.Channel.GetScoreTableByAmount_Code(amount_Code);
        }
        
        public int GetScoreModel(string dimensionCode) {
            return base.Channel.GetScoreModel(dimensionCode);
        }
        
        public string GetFormulaStrByDimensionCode(string dimensionCode) {
            return base.Channel.GetFormulaStrByDimensionCode(dimensionCode);
        }
        
        public System.Data.DataTable GetFormulaStrByDimensionCodeList(string dimensionCodeList) {
            return base.Channel.GetFormulaStrByDimensionCodeList(dimensionCodeList);
        }
        
        public string GetDimensionName(string dimensionCode) {
            return base.Channel.GetDimensionName(dimensionCode);
        }
        
        public string NormCodeByDimensionCode(string dimensionCode) {
            return base.Channel.NormCodeByDimensionCode(dimensionCode);
        }
        
        public System.Data.DataTable NormCodeByDimensionCodeList(string dimensionCodeList) {
            return base.Channel.NormCodeByDimensionCodeList(dimensionCodeList);
        }
        
        public System.Data.DataTable GetExplainScoreByNormCodeTable(string normCodeList) {
            return base.Channel.GetExplainScoreByNormCodeTable(normCodeList);
        }
        
        public System.Collections.Generic.List<CrisisInterfere.GroupReportService.ExplainModel> GetExplainScoreByNormCode(string normCode) {
            return base.Channel.GetExplainScoreByNormCode(normCode);
        }
        
        public System.Collections.Generic.List<CrisisInterfere.GroupReportService.NormWarningModel> GetNormWarningByNormCode(string normCode) {
            return base.Channel.GetNormWarningByNormCode(normCode);
        }
        
        public System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<CrisisInterfere.GroupReportService.NormWarningModel>> GetNormWarningByNormCodeList(string normCodeList) {
            return base.Channel.GetNormWarningByNormCodeList(normCodeList);
        }
        
        public string GetAnswerCreateTimeByUID(int uID) {
            return base.Channel.GetAnswerCreateTimeByUID(uID);
        }
        
        public System.Collections.Generic.List<string> GetAnswerCreateTimeByUIDList(string uID) {
            return base.Channel.GetAnswerCreateTimeByUIDList(uID);
        }
        
        public string GetGroupReportCreateTime(int grID) {
            return base.Channel.GetGroupReportCreateTime(grID);
        }
        
        public int GetReportByReportName(string reportName, string enterpriseCode) {
            return base.Channel.GetReportByReportName(reportName, enterpriseCode);
        }
        
        public int GetScoreByAnswerID(int answerID) {
            return base.Channel.GetScoreByAnswerID(answerID);
        }
    }
}
