//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrisisInterfere.IndexService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IndexModularSearchModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.IndexModel")]
    [System.SerializableAttribute()]
    public partial class IndexModularSearchModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IndexModularViewModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.IndexModel")]
    [System.SerializableAttribute()]
    public partial class IndexModularViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AppointmentPeopleCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiscriminateEstiamteCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DynamicEstimateCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdioctoniaEstimateCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonalReportCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PotentialRiskEstimateCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AppointmentPeopleCount {
            get {
                return this.AppointmentPeopleCountField;
            }
            set {
                if ((this.AppointmentPeopleCountField.Equals(value) != true)) {
                    this.AppointmentPeopleCountField = value;
                    this.RaisePropertyChanged("AppointmentPeopleCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiscriminateEstiamteCount {
            get {
                return this.DiscriminateEstiamteCountField;
            }
            set {
                if ((this.DiscriminateEstiamteCountField.Equals(value) != true)) {
                    this.DiscriminateEstiamteCountField = value;
                    this.RaisePropertyChanged("DiscriminateEstiamteCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DynamicEstimateCount {
            get {
                return this.DynamicEstimateCountField;
            }
            set {
                if ((this.DynamicEstimateCountField.Equals(value) != true)) {
                    this.DynamicEstimateCountField = value;
                    this.RaisePropertyChanged("DynamicEstimateCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdioctoniaEstimateCount {
            get {
                return this.IdioctoniaEstimateCountField;
            }
            set {
                if ((this.IdioctoniaEstimateCountField.Equals(value) != true)) {
                    this.IdioctoniaEstimateCountField = value;
                    this.RaisePropertyChanged("IdioctoniaEstimateCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonalReportCount {
            get {
                return this.PersonalReportCountField;
            }
            set {
                if ((this.PersonalReportCountField.Equals(value) != true)) {
                    this.PersonalReportCountField = value;
                    this.RaisePropertyChanged("PersonalReportCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PotentialRiskEstimateCount {
            get {
                return this.PotentialRiskEstimateCountField;
            }
            set {
                if ((this.PotentialRiskEstimateCountField.Equals(value) != true)) {
                    this.PotentialRiskEstimateCountField = value;
                    this.RaisePropertyChanged("PotentialRiskEstimateCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IndexService.IIndexService")]
    public interface IIndexService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIndexService/GetModularTemp", ReplyAction="http://tempuri.org/IIndexService/GetModularTempResponse")]
        System.Data.DataSet GetModularTemp(string loginName, string EnterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIndexService/SaveModelSet", ReplyAction="http://tempuri.org/IIndexService/SaveModelSetResponse")]
        int SaveModelSet(string LoginName, string ModularSetStr, string EnterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIndexService/GetModularStrByLoginName", ReplyAction="http://tempuri.org/IIndexService/GetModularStrByLoginNameResponse")]
        System.Data.DataTable GetModularStrByLoginName(string LoginName, string EnterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIndexService/GetIndexModularViewCount", ReplyAction="http://tempuri.org/IIndexService/GetIndexModularViewCountResponse")]
        CrisisInterfere.IndexService.IndexModularViewModel GetIndexModularViewCount(CrisisInterfere.IndexService.IndexModularSearchModel model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIndexServiceChannel : CrisisInterfere.IndexService.IIndexService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IndexServiceClient : System.ServiceModel.ClientBase<CrisisInterfere.IndexService.IIndexService>, CrisisInterfere.IndexService.IIndexService {
        
        public IndexServiceClient() {
        }
        
        public IndexServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IndexServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndexServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndexServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetModularTemp(string loginName, string EnterpriseCode) {
            return base.Channel.GetModularTemp(loginName, EnterpriseCode);
        }
        
        public int SaveModelSet(string LoginName, string ModularSetStr, string EnterpriseCode) {
            return base.Channel.SaveModelSet(LoginName, ModularSetStr, EnterpriseCode);
        }
        
        public System.Data.DataTable GetModularStrByLoginName(string LoginName, string EnterpriseCode) {
            return base.Channel.GetModularStrByLoginName(LoginName, EnterpriseCode);
        }
        
        public CrisisInterfere.IndexService.IndexModularViewModel GetIndexModularViewCount(CrisisInterfere.IndexService.IndexModularSearchModel model) {
            return base.Channel.GetIndexModularViewCount(model);
        }
    }
}
