//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrisisInterfere.PotentialRiskEstimateService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PotentialRiskEstimateSearchModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.PotentialRiskEstimateM" +
        "odel")]
    [System.SerializableAttribute()]
    public partial class PotentialRiskEstimateSearchModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisposalStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WarningLevelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmountCode {
            get {
                return this.AmountCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountCodeField, value) != true)) {
                    this.AmountCodeField = value;
                    this.RaisePropertyChanged("AmountCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((this.DepartmentIDField.Equals(value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisposalState {
            get {
                return this.DisposalStateField;
            }
            set {
                if ((this.DisposalStateField.Equals(value) != true)) {
                    this.DisposalStateField = value;
                    this.RaisePropertyChanged("DisposalState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndIndex {
            get {
                return this.EndIndexField;
            }
            set {
                if ((this.EndIndexField.Equals(value) != true)) {
                    this.EndIndexField = value;
                    this.RaisePropertyChanged("EndIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EndTimeField, value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartIndex {
            get {
                return this.StartIndexField;
            }
            set {
                if ((this.StartIndexField.Equals(value) != true)) {
                    this.StartIndexField = value;
                    this.RaisePropertyChanged("StartIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StartTimeField, value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WarningLevel {
            get {
                return this.WarningLevelField;
            }
            set {
                if ((this.WarningLevelField.Equals(value) != true)) {
                    this.WarningLevelField = value;
                    this.RaisePropertyChanged("WarningLevel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportPersonalInfoModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.CommonModel")]
    [System.SerializableAttribute()]
    public partial class ReportPersonalInfoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisposalStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TestTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarningStateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Age {
            get {
                return this.AgeField;
            }
            set {
                if ((object.ReferenceEquals(this.AgeField, value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellPhone {
            get {
                return this.CellPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CellPhoneField, value) != true)) {
                    this.CellPhoneField = value;
                    this.RaisePropertyChanged("CellPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisposalState {
            get {
                return this.DisposalStateField;
            }
            set {
                if ((object.ReferenceEquals(this.DisposalStateField, value) != true)) {
                    this.DisposalStateField = value;
                    this.RaisePropertyChanged("DisposalState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TestDate {
            get {
                return this.TestDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TestDateField, value) != true)) {
                    this.TestDateField = value;
                    this.RaisePropertyChanged("TestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TestType {
            get {
                return this.TestTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TestTypeField, value) != true)) {
                    this.TestTypeField = value;
                    this.RaisePropertyChanged("TestType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarningState {
            get {
                return this.WarningStateField;
            }
            set {
                if ((object.ReferenceEquals(this.WarningStateField, value) != true)) {
                    this.WarningStateField = value;
                    this.RaisePropertyChanged("WarningState");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PotentialRiskEstimateService.IPotentialRiskEstimateService")]
    public interface IPotentialRiskEstimateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPotentialRiskEstimateService/InitialPotentialRiskEstimateTabl" +
            "e", ReplyAction="http://tempuri.org/IPotentialRiskEstimateService/InitialPotentialRiskEstimateTabl" +
            "eResponse")]
        System.Data.DataSet InitialPotentialRiskEstimateTable(CrisisInterfere.PotentialRiskEstimateService.PotentialRiskEstimateSearchModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPotentialRiskEstimateService/GetResultTableByBelongToCode", ReplyAction="http://tempuri.org/IPotentialRiskEstimateService/GetResultTableByBelongToCodeResp" +
            "onse")]
        System.Data.DataTable GetResultTableByBelongToCode(string belongToCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPotentialRiskEstimateService/GetSuggestionByBelongToCode", ReplyAction="http://tempuri.org/IPotentialRiskEstimateService/GetSuggestionByBelongToCodeRespo" +
            "nse")]
        string GetSuggestionByBelongToCode(string belongToCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPotentialRiskEstimateService/AddSuggestion", ReplyAction="http://tempuri.org/IPotentialRiskEstimateService/AddSuggestionResponse")]
        int AddSuggestion(string suggestion, string belongToCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPotentialRiskEstimateService/GetPotentialRiskEstimateReportIn" +
            "foByBelongToCode", ReplyAction="http://tempuri.org/IPotentialRiskEstimateService/GetPotentialRiskEstimateReportIn" +
            "foByBelongToCodeResponse")]
        CrisisInterfere.PotentialRiskEstimateService.ReportPersonalInfoModel GetPotentialRiskEstimateReportInfoByBelongToCode(string belongToCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPotentialRiskEstimateServiceChannel : CrisisInterfere.PotentialRiskEstimateService.IPotentialRiskEstimateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PotentialRiskEstimateServiceClient : System.ServiceModel.ClientBase<CrisisInterfere.PotentialRiskEstimateService.IPotentialRiskEstimateService>, CrisisInterfere.PotentialRiskEstimateService.IPotentialRiskEstimateService {
        
        public PotentialRiskEstimateServiceClient() {
        }
        
        public PotentialRiskEstimateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PotentialRiskEstimateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PotentialRiskEstimateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PotentialRiskEstimateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet InitialPotentialRiskEstimateTable(CrisisInterfere.PotentialRiskEstimateService.PotentialRiskEstimateSearchModel model) {
            return base.Channel.InitialPotentialRiskEstimateTable(model);
        }
        
        public System.Data.DataTable GetResultTableByBelongToCode(string belongToCode) {
            return base.Channel.GetResultTableByBelongToCode(belongToCode);
        }
        
        public string GetSuggestionByBelongToCode(string belongToCode) {
            return base.Channel.GetSuggestionByBelongToCode(belongToCode);
        }
        
        public int AddSuggestion(string suggestion, string belongToCode) {
            return base.Channel.AddSuggestion(suggestion, belongToCode);
        }
        
        public CrisisInterfere.PotentialRiskEstimateService.ReportPersonalInfoModel GetPotentialRiskEstimateReportInfoByBelongToCode(string belongToCode) {
            return base.Channel.GetPotentialRiskEstimateReportInfoByBelongToCode(belongToCode);
        }
    }
}
