//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrisisInterfere.CrisisInterfereSolutionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrisisInterfereSolutionSearchModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.CrisisInterfereSolutio" +
        "nModel")]
    [System.SerializableAttribute()]
    public partial class CrisisInterfereSolutionSearchModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SolutionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartIndexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndIndex {
            get {
                return this.EndIndexField;
            }
            set {
                if ((this.EndIndexField.Equals(value) != true)) {
                    this.EndIndexField = value;
                    this.RaisePropertyChanged("EndIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SolutionType {
            get {
                return this.SolutionTypeField;
            }
            set {
                if ((this.SolutionTypeField.Equals(value) != true)) {
                    this.SolutionTypeField = value;
                    this.RaisePropertyChanged("SolutionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartIndex {
            get {
                return this.StartIndexField;
            }
            set {
                if ((this.StartIndexField.Equals(value) != true)) {
                    this.StartIndexField = value;
                    this.RaisePropertyChanged("StartIndex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrisisInterfereSolutionModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.CrisisInterfereSolutio" +
        "nModel")]
    [System.SerializableAttribute()]
    public partial class CrisisInterfereSolutionModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CISContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CISTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int STIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CISContent {
            get {
                return this.CISContentField;
            }
            set {
                if ((object.ReferenceEquals(this.CISContentField, value) != true)) {
                    this.CISContentField = value;
                    this.RaisePropertyChanged("CISContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CISTitle {
            get {
                return this.CISTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.CISTitleField, value) != true)) {
                    this.CISTitleField = value;
                    this.RaisePropertyChanged("CISTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int STID {
            get {
                return this.STIDField;
            }
            set {
                if ((this.STIDField.Equals(value) != true)) {
                    this.STIDField = value;
                    this.RaisePropertyChanged("STID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CrisisInterfereSolutionService.ICrisisInterfereSolutionService")]
    public interface ICrisisInterfereSolutionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrisisInterfereSolutionService/InitialTable", ReplyAction="http://tempuri.org/ICrisisInterfereSolutionService/InitialTableResponse")]
        System.Data.DataSet InitialTable(CrisisInterfere.CrisisInterfereSolutionService.CrisisInterfereSolutionSearchModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrisisInterfereSolutionService/GetCrisisInterfereSolutionCont" +
            "entByID", ReplyAction="http://tempuri.org/ICrisisInterfereSolutionService/GetCrisisInterfereSolutionCont" +
            "entByIDResponse")]
        string GetCrisisInterfereSolutionContentByID(int cISID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrisisInterfereSolutionService/AddCrisisInterfereSolution", ReplyAction="http://tempuri.org/ICrisisInterfereSolutionService/AddCrisisInterfereSolutionResp" +
            "onse")]
        int AddCrisisInterfereSolution(CrisisInterfere.CrisisInterfereSolutionService.CrisisInterfereSolutionModel model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrisisInterfereSolutionServiceChannel : CrisisInterfere.CrisisInterfereSolutionService.ICrisisInterfereSolutionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrisisInterfereSolutionServiceClient : System.ServiceModel.ClientBase<CrisisInterfere.CrisisInterfereSolutionService.ICrisisInterfereSolutionService>, CrisisInterfere.CrisisInterfereSolutionService.ICrisisInterfereSolutionService {
        
        public CrisisInterfereSolutionServiceClient() {
        }
        
        public CrisisInterfereSolutionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrisisInterfereSolutionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrisisInterfereSolutionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrisisInterfereSolutionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet InitialTable(CrisisInterfere.CrisisInterfereSolutionService.CrisisInterfereSolutionSearchModel model) {
            return base.Channel.InitialTable(model);
        }
        
        public string GetCrisisInterfereSolutionContentByID(int cISID) {
            return base.Channel.GetCrisisInterfereSolutionContentByID(cISID);
        }
        
        public int AddCrisisInterfereSolution(CrisisInterfere.CrisisInterfereSolutionService.CrisisInterfereSolutionModel model) {
            return base.Channel.AddCrisisInterfereSolution(model);
        }
    }
}
