//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrisisInterfere.WorkArchivesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkArchivesSearchModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.WorkArchivesModel")]
    [System.SerializableAttribute()]
    public partial class WorkArchivesSearchModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((this.DepartmentIDField.Equals(value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EndTimeField, value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StartTimeField, value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WarningPeopleViewModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.WorkArchivesModel")]
    [System.SerializableAttribute()]
    public partial class WarningPeopleViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HigherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HighestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MediumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Higher {
            get {
                return this.HigherField;
            }
            set {
                if ((this.HigherField.Equals(value) != true)) {
                    this.HigherField = value;
                    this.RaisePropertyChanged("Higher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Highest {
            get {
                return this.HighestField;
            }
            set {
                if ((this.HighestField.Equals(value) != true)) {
                    this.HighestField = value;
                    this.RaisePropertyChanged("Highest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Lower {
            get {
                return this.LowerField;
            }
            set {
                if ((this.LowerField.Equals(value) != true)) {
                    this.LowerField = value;
                    this.RaisePropertyChanged("Lower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Medium {
            get {
                return this.MediumField;
            }
            set {
                if ((this.MediumField.Equals(value) != true)) {
                    this.MediumField = value;
                    this.RaisePropertyChanged("Medium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NA {
            get {
                return this.NAField;
            }
            set {
                if ((this.NAField.Equals(value) != true)) {
                    this.NAField = value;
                    this.RaisePropertyChanged("NA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CounselorWorkStatisticsViewModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.WorkArchivesModel")]
    [System.SerializableAttribute()]
    public partial class CounselorWorkStatisticsViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AppointmentPeopleCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CounselorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisposalPeopleCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AppointmentPeopleCount {
            get {
                return this.AppointmentPeopleCountField;
            }
            set {
                if ((this.AppointmentPeopleCountField.Equals(value) != true)) {
                    this.AppointmentPeopleCountField = value;
                    this.RaisePropertyChanged("AppointmentPeopleCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CounselorName {
            get {
                return this.CounselorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CounselorNameField, value) != true)) {
                    this.CounselorNameField = value;
                    this.RaisePropertyChanged("CounselorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisposalPeopleCount {
            get {
                return this.DisposalPeopleCountField;
            }
            set {
                if ((this.DisposalPeopleCountField.Equals(value) != true)) {
                    this.DisposalPeopleCountField = value;
                    this.RaisePropertyChanged("DisposalPeopleCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultQuestionTypePeopleCountViewModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.WorkArchivesModel")]
    [System.SerializableAttribute()]
    public partial class ConsultQuestionTypePeopleCountViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MarriageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MoodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OtherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SocietyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Action {
            get {
                return this.ActionField;
            }
            set {
                if ((this.ActionField.Equals(value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Job {
            get {
                return this.JobField;
            }
            set {
                if ((this.JobField.Equals(value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Marriage {
            get {
                return this.MarriageField;
            }
            set {
                if ((this.MarriageField.Equals(value) != true)) {
                    this.MarriageField = value;
                    this.RaisePropertyChanged("Marriage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mood {
            get {
                return this.MoodField;
            }
            set {
                if ((this.MoodField.Equals(value) != true)) {
                    this.MoodField = value;
                    this.RaisePropertyChanged("Mood");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Other {
            get {
                return this.OtherField;
            }
            set {
                if ((this.OtherField.Equals(value) != true)) {
                    this.OtherField = value;
                    this.RaisePropertyChanged("Other");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Parentage {
            get {
                return this.ParentageField;
            }
            set {
                if ((this.ParentageField.Equals(value) != true)) {
                    this.ParentageField = value;
                    this.RaisePropertyChanged("Parentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Personal {
            get {
                return this.PersonalField;
            }
            set {
                if ((this.PersonalField.Equals(value) != true)) {
                    this.PersonalField = value;
                    this.RaisePropertyChanged("Personal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Society {
            get {
                return this.SocietyField;
            }
            set {
                if ((this.SocietyField.Equals(value) != true)) {
                    this.SocietyField = value;
                    this.RaisePropertyChanged("Society");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Studies {
            get {
                return this.StudiesField;
            }
            set {
                if ((this.StudiesField.Equals(value) != true)) {
                    this.StudiesField = value;
                    this.RaisePropertyChanged("Studies");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeriousLevelViewModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.WorkArchivesModel")]
    [System.SerializableAttribute()]
    public partial class SeriousLevelViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FirstLevelPeopleCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FithLevelPeopleCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FouthLevelPeopleCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecondLevelPeopleCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ThirdLevelPeopleCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstLevelPeopleCount {
            get {
                return this.FirstLevelPeopleCountField;
            }
            set {
                if ((this.FirstLevelPeopleCountField.Equals(value) != true)) {
                    this.FirstLevelPeopleCountField = value;
                    this.RaisePropertyChanged("FirstLevelPeopleCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FithLevelPeopleCount {
            get {
                return this.FithLevelPeopleCountField;
            }
            set {
                if ((this.FithLevelPeopleCountField.Equals(value) != true)) {
                    this.FithLevelPeopleCountField = value;
                    this.RaisePropertyChanged("FithLevelPeopleCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FouthLevelPeopleCount {
            get {
                return this.FouthLevelPeopleCountField;
            }
            set {
                if ((this.FouthLevelPeopleCountField.Equals(value) != true)) {
                    this.FouthLevelPeopleCountField = value;
                    this.RaisePropertyChanged("FouthLevelPeopleCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionTypeName {
            get {
                return this.QuestionTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionTypeNameField, value) != true)) {
                    this.QuestionTypeNameField = value;
                    this.RaisePropertyChanged("QuestionTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecondLevelPeopleCount {
            get {
                return this.SecondLevelPeopleCountField;
            }
            set {
                if ((this.SecondLevelPeopleCountField.Equals(value) != true)) {
                    this.SecondLevelPeopleCountField = value;
                    this.RaisePropertyChanged("SecondLevelPeopleCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ThirdLevelPeopleCount {
            get {
                return this.ThirdLevelPeopleCountField;
            }
            set {
                if ((this.ThirdLevelPeopleCountField.Equals(value) != true)) {
                    this.ThirdLevelPeopleCountField = value;
                    this.RaisePropertyChanged("ThirdLevelPeopleCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisposalDistributionPeopleCountModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.WorkArchivesModel")]
    [System.SerializableAttribute()]
    public partial class DisposalDistributionPeopleCountModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AllDayCustodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoHeartConsultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NotNeedHelpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoticeAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeeDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AllDayCustody {
            get {
                return this.AllDayCustodyField;
            }
            set {
                if ((this.AllDayCustodyField.Equals(value) != true)) {
                    this.AllDayCustodyField = value;
                    this.RaisePropertyChanged("AllDayCustody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GoHeartConsult {
            get {
                return this.GoHeartConsultField;
            }
            set {
                if ((this.GoHeartConsultField.Equals(value) != true)) {
                    this.GoHeartConsultField = value;
                    this.RaisePropertyChanged("GoHeartConsult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NotNeedHelp {
            get {
                return this.NotNeedHelpField;
            }
            set {
                if ((this.NotNeedHelpField.Equals(value) != true)) {
                    this.NotNeedHelpField = value;
                    this.RaisePropertyChanged("NotNeedHelp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoticeAdmin {
            get {
                return this.NoticeAdminField;
            }
            set {
                if ((this.NoticeAdminField.Equals(value) != true)) {
                    this.NoticeAdminField = value;
                    this.RaisePropertyChanged("NoticeAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeeD {
            get {
                return this.SeeDField;
            }
            set {
                if ((this.SeeDField.Equals(value) != true)) {
                    this.SeeDField = value;
                    this.RaisePropertyChanged("SeeD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorkArchivesService.IWorkArchivesService")]
    public interface IWorkArchivesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkArchivesService/GetPotentialRiskWarningPeopleCount", ReplyAction="http://tempuri.org/IWorkArchivesService/GetPotentialRiskWarningPeopleCountRespons" +
            "e")]
        CrisisInterfere.WorkArchivesService.WarningPeopleViewModel GetPotentialRiskWarningPeopleCount(CrisisInterfere.WorkArchivesService.WorkArchivesSearchModel searchModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkArchivesService/GetIdioctoniaWarningPeopleCount", ReplyAction="http://tempuri.org/IWorkArchivesService/GetIdioctoniaWarningPeopleCountResponse")]
        CrisisInterfere.WorkArchivesService.WarningPeopleViewModel GetIdioctoniaWarningPeopleCount(CrisisInterfere.WorkArchivesService.WorkArchivesSearchModel searchModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkArchivesService/GetDiscernEstimateWarningPeopleCount", ReplyAction="http://tempuri.org/IWorkArchivesService/GetDiscernEstimateWarningPeopleCountRespo" +
            "nse")]
        CrisisInterfere.WorkArchivesService.WarningPeopleViewModel GetDiscernEstimateWarningPeopleCount(CrisisInterfere.WorkArchivesService.WorkArchivesSearchModel searchModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkArchivesService/GetDynamicEstimateWarningPeopleCount", ReplyAction="http://tempuri.org/IWorkArchivesService/GetDynamicEstimateWarningPeopleCountRespo" +
            "nse")]
        CrisisInterfere.WorkArchivesService.WarningPeopleViewModel GetDynamicEstimateWarningPeopleCount(CrisisInterfere.WorkArchivesService.WorkArchivesSearchModel searchModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkArchivesService/GetCounselorWorkStatisticsByDepartmentID", ReplyAction="http://tempuri.org/IWorkArchivesService/GetCounselorWorkStatisticsByDepartmentIDR" +
            "esponse")]
        System.Collections.Generic.List<CrisisInterfere.WorkArchivesService.CounselorWorkStatisticsViewModel> GetCounselorWorkStatisticsByDepartmentID(CrisisInterfere.WorkArchivesService.WorkArchivesSearchModel searchModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkArchivesService/GetQuestionTypeConsultPeopleCount", ReplyAction="http://tempuri.org/IWorkArchivesService/GetQuestionTypeConsultPeopleCountResponse" +
            "")]
        CrisisInterfere.WorkArchivesService.ConsultQuestionTypePeopleCountViewModel GetQuestionTypeConsultPeopleCount(CrisisInterfere.WorkArchivesService.WorkArchivesSearchModel searchModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkArchivesService/GetQuestionTypeSeriousLevelPeopleCount", ReplyAction="http://tempuri.org/IWorkArchivesService/GetQuestionTypeSeriousLevelPeopleCountRes" +
            "ponse")]
        System.Collections.Generic.List<CrisisInterfere.WorkArchivesService.SeriousLevelViewModel> GetQuestionTypeSeriousLevelPeopleCount(CrisisInterfere.WorkArchivesService.WorkArchivesSearchModel searchModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkArchivesService/GetSeriousLevelPeopleCount", ReplyAction="http://tempuri.org/IWorkArchivesService/GetSeriousLevelPeopleCountResponse")]
        CrisisInterfere.WorkArchivesService.SeriousLevelViewModel GetSeriousLevelPeopleCount(CrisisInterfere.WorkArchivesService.WorkArchivesSearchModel searchModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkArchivesService/GetDisposalDistributionPeopleCount", ReplyAction="http://tempuri.org/IWorkArchivesService/GetDisposalDistributionPeopleCountRespons" +
            "e")]
        CrisisInterfere.WorkArchivesService.DisposalDistributionPeopleCountModel GetDisposalDistributionPeopleCount(CrisisInterfere.WorkArchivesService.WorkArchivesSearchModel searchModel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWorkArchivesServiceChannel : CrisisInterfere.WorkArchivesService.IWorkArchivesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkArchivesServiceClient : System.ServiceModel.ClientBase<CrisisInterfere.WorkArchivesService.IWorkArchivesService>, CrisisInterfere.WorkArchivesService.IWorkArchivesService {
        
        public WorkArchivesServiceClient() {
        }
        
        public WorkArchivesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkArchivesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkArchivesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkArchivesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CrisisInterfere.WorkArchivesService.WarningPeopleViewModel GetPotentialRiskWarningPeopleCount(CrisisInterfere.WorkArchivesService.WorkArchivesSearchModel searchModel) {
            return base.Channel.GetPotentialRiskWarningPeopleCount(searchModel);
        }
        
        public CrisisInterfere.WorkArchivesService.WarningPeopleViewModel GetIdioctoniaWarningPeopleCount(CrisisInterfere.WorkArchivesService.WorkArchivesSearchModel searchModel) {
            return base.Channel.GetIdioctoniaWarningPeopleCount(searchModel);
        }
        
        public CrisisInterfere.WorkArchivesService.WarningPeopleViewModel GetDiscernEstimateWarningPeopleCount(CrisisInterfere.WorkArchivesService.WorkArchivesSearchModel searchModel) {
            return base.Channel.GetDiscernEstimateWarningPeopleCount(searchModel);
        }
        
        public CrisisInterfere.WorkArchivesService.WarningPeopleViewModel GetDynamicEstimateWarningPeopleCount(CrisisInterfere.WorkArchivesService.WorkArchivesSearchModel searchModel) {
            return base.Channel.GetDynamicEstimateWarningPeopleCount(searchModel);
        }
        
        public System.Collections.Generic.List<CrisisInterfere.WorkArchivesService.CounselorWorkStatisticsViewModel> GetCounselorWorkStatisticsByDepartmentID(CrisisInterfere.WorkArchivesService.WorkArchivesSearchModel searchModel) {
            return base.Channel.GetCounselorWorkStatisticsByDepartmentID(searchModel);
        }
        
        public CrisisInterfere.WorkArchivesService.ConsultQuestionTypePeopleCountViewModel GetQuestionTypeConsultPeopleCount(CrisisInterfere.WorkArchivesService.WorkArchivesSearchModel searchModel) {
            return base.Channel.GetQuestionTypeConsultPeopleCount(searchModel);
        }
        
        public System.Collections.Generic.List<CrisisInterfere.WorkArchivesService.SeriousLevelViewModel> GetQuestionTypeSeriousLevelPeopleCount(CrisisInterfere.WorkArchivesService.WorkArchivesSearchModel searchModel) {
            return base.Channel.GetQuestionTypeSeriousLevelPeopleCount(searchModel);
        }
        
        public CrisisInterfere.WorkArchivesService.SeriousLevelViewModel GetSeriousLevelPeopleCount(CrisisInterfere.WorkArchivesService.WorkArchivesSearchModel searchModel) {
            return base.Channel.GetSeriousLevelPeopleCount(searchModel);
        }
        
        public CrisisInterfere.WorkArchivesService.DisposalDistributionPeopleCountModel GetDisposalDistributionPeopleCount(CrisisInterfere.WorkArchivesService.WorkArchivesSearchModel searchModel) {
            return base.Channel.GetDisposalDistributionPeopleCount(searchModel);
        }
    }
}
