//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrisisInterfere.PresentationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PresentationService.IPresentationService")]
    public interface IPresentationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPresentationService/GetAmountTempByCode", ReplyAction="http://tempuri.org/IPresentationService/GetAmountTempByCodeResponse")]
        System.Data.DataTable GetAmountTempByCode(string A_Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPresentationService/GetAnswerTemp", ReplyAction="http://tempuri.org/IPresentationService/GetAnswerTempResponse")]
        System.Data.DataTable GetAnswerTemp(int AnswerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPresentationService/GetDimensionTemp", ReplyAction="http://tempuri.org/IPresentationService/GetDimensionTempResponse")]
        System.Data.DataSet GetDimensionTemp(string AmountCode, int AnswerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPresentationService/GetDMaxMin", ReplyAction="http://tempuri.org/IPresentationService/GetDMaxMinResponse")]
        System.Data.DataTable GetDMaxMin(string WDCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPresentationService/GetSingleBySbjCodeAndOptCode", ReplyAction="http://tempuri.org/IPresentationService/GetSingleBySbjCodeAndOptCodeResponse")]
        System.Data.DataTable GetSingleBySbjCodeAndOptCode(string subjectCode, string optionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPresentationService/GetNumber", ReplyAction="http://tempuri.org/IPresentationService/GetNumberResponse")]
        System.Data.DataTable GetNumber(string TZcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPresentationService/GetDimensionTempBycode", ReplyAction="http://tempuri.org/IPresentationService/GetDimensionTempBycodeResponse")]
        System.Data.DataSet GetDimensionTempBycode(string AmountCode, int UID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPresentationServiceChannel : CrisisInterfere.PresentationService.IPresentationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PresentationServiceClient : System.ServiceModel.ClientBase<CrisisInterfere.PresentationService.IPresentationService>, CrisisInterfere.PresentationService.IPresentationService {
        
        public PresentationServiceClient() {
        }
        
        public PresentationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PresentationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PresentationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PresentationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetAmountTempByCode(string A_Code) {
            return base.Channel.GetAmountTempByCode(A_Code);
        }
        
        public System.Data.DataTable GetAnswerTemp(int AnswerID) {
            return base.Channel.GetAnswerTemp(AnswerID);
        }
        
        public System.Data.DataSet GetDimensionTemp(string AmountCode, int AnswerID) {
            return base.Channel.GetDimensionTemp(AmountCode, AnswerID);
        }
        
        public System.Data.DataTable GetDMaxMin(string WDCode) {
            return base.Channel.GetDMaxMin(WDCode);
        }
        
        public System.Data.DataTable GetSingleBySbjCodeAndOptCode(string subjectCode, string optionCode) {
            return base.Channel.GetSingleBySbjCodeAndOptCode(subjectCode, optionCode);
        }
        
        public System.Data.DataTable GetNumber(string TZcode) {
            return base.Channel.GetNumber(TZcode);
        }
        
        public System.Data.DataSet GetDimensionTempBycode(string AmountCode, int UID) {
            return base.Channel.GetDimensionTempBycode(AmountCode, UID);
        }
    }
}
